### PR TITLE
Skipping a dependent parser.

### LINKED ISSUE #26: Skipping a dependent parser
What happens if user provides a **--skip** action for a *parser* which is the *dependency of an other*? We should *warn the user* about this in a log message.

### PR DESCRIPTION
**Pull request by csordasmarton**
This commit resolves #26 issue.

### CODE REVIEW

**Comment by bruntib** [comment]
Why is the vector of skipped parsers the member of the constructor? This should be given to `loadPlugins()`.

**Comment by csordasmarton** [comment]
We are using this vector in multiple functions: `loadPlugins`, `getTopologicalOrder`. This way you may ask that why is the plugin directory (_pluginDir) is a member of the constructor.

**Comment by bruntib** [comment]
I thought we should eliminate dependencies between plugins. There is no dependency at all. I don't even know if we ever had such a dependency. What do you think?

**Comment by mcserep** [comment]
I have already brought this topic up previusly, but this is maybe also a point, where we shall consider how the LSP service will be added to architecture.
Right now the functionality is implemented as a service (see the `lsp` branch), in the `service` folder, beside the `ProjectService`, `LanguageService`, etc. However it also depends on the functionality of the `cpp` plugin, which shall be probably revised in the near future.

What shall the LSP functionality be?
 * A separate, standalone plugin? In that case it will be dependant on other language plugins.
 * Or each language plugin (`cpp`, `java`, etc.) shall have an own LSP service functionality - in case they support this feature? With this approach there is no need for dependant plugins.

**Comment by bruntib** [comment]
This ticket is related only to the parsers. The dependency in this context means that a parser plugin can communicate through the parser API which other parsers should run before this one (see: https://github.com/Ericsson/CodeCompass/blob/0e841099cd534f6079a6770291d2edc2a36afd8a/parser/include/parser/abstractparser.h#L34). So I suggest to eliminate this `getDependentParsers()` function from the abstract parser and all the related logic. I added you as a reviewer to this ticket because incremental parsing functionality also added some extra logic to this unnecessary dependency handling.

Some history: in the ancient times there was an idea that the search parser could use C++ related tables in order to make its own findings more precise. For example this way the search parser could tell about a symbol whether it's a declaration or definition, etc. That's why it would be important to run C++ parser first. But I have never seen this relationship between the C++ and search parsers. At least in Flash version there isn't such a relationship for sure. And that's why I suggest that this dependency between parsers could be eliminated.

**Comment by mcserep** [comment]
I misunderstood it for a complete plugin dependency; sorry for not reading it through properly, my previous comment can be ignored :)

In this case there is no known **parser** dependency for me. Incremental parsing handles the dependency chain of the parsers and executes 5 steps:
1.  All files directly modified or deleted are marked so.
2.  All plugin parsers  (in a reverse topological order) mark the files which they think changed indirectly.
3.  All plugin parsers (also in a reverse topological order) clean up the database (and the workspace). They have the information which files have changed based on any parser.
4.  The common tables are cleaned up.
5.  All parsers execute the parsing (in a topological order).

If there are no dependencies between the parsers, it will still work correctly. The topological ordering of the parsers can be also removed in that case.

**Comment by bruntib** [comment]
No problem, it's fine :)
So if everyone agrees, I'll remove this dependency stuff.
Thanks for the bullet points, I'll consider them during the refactoring.

**Comment by bruntib** [comment]
The dependency relationship has been eliminated in #362 so this pull request is relevant no more.

**Pull request closed without merging**
