### PR TITLE
Startpage of the new Flash release.

### PR DESCRIPTION
**Pull request by csordasmarton**
Startpage of the new Flash release.

### CODE REVIEW

**Comment by whisperity** [comment]
Does this mean that the changelog of the older versions are lost forever now?

**Comment by csordasmarton** [comment]
@whisperity:  I removed the changelog in this release because we rewrited the whole CodeCompass project and it doesn't contain every old features like python parser, java parser, file diagrams and other stuffs for now. If it's necessary we can put the old history at the bottom of this startpage. What do you think @bruntib?

**Comment by csordasmarton** [comment]
@bruntib Why did you move the `git.png` to a common place? 
```
plugins/git/webgui/images/git.png → webgui/images/git.png
```
Plugin specific things have to be stored in the directory of the plugin.

**Comment by bruntib** [comment]
Because on the startpage this picture didn't appear, since the URL referred to the common `webgui/images/git.png` location. By the way it is a good idea to store plugin specific things in the plugin, but the question is how such a common code will know about that? Should the startpage also be pluginable?

**Comment by csordasmarton** [comment]
In the [CMakeLists.txt](https://github.com/Ericsson/CodeCompass/blob/master/plugins/git/CMakeLists.txt) of the git plugin we called the [install_webplugin](https://github.com/Ericsson/CodeCompass/blob/master/Functions.cmake) function which installes the images to the common directory (`/share/codecompass/webgui/images`) of the CodeCompass installation directory. The startpage loads the images from this directory. You should check that git.png was in this directory after `make install` (`make clean` and `make install` can solve this problem if it's not). You can see the metrics plugin as an example. It works.
In the startpage we listed some main feature of CodeCompass (metrics, diagrams etc.). I think it's our job if anyone writes a good plugin/feature to decide, it can be shown in the startpage.

**Comment by bruntib** [comment]
OK, thanks, I'll check the install command.

**Pull request merged**
