### PR TITLE
Generate .sql files into the build directory

### LINKED ISSUE #253: .sql files should be generated in build directory
When compiling the project, odb generates .sql files to the source directory instead of the build directory. This results that recompilation of CodeCompass with another database system leaves the old .sql files and those will be installed:

```.sh
cmake -DDATABASE=sqlite ...
make install
make clean
cmake -DDATABASE=pgsql ...
make install  # This installs .sql files in SQLite format
```

### PR DESCRIPTION
**Pull request by mcserep**
Resolves #253 .

### CODE REVIEW

**Comment by mcserep** [comment]
@bruntib: fixed it, please reevaluate it.

**Comment by bruntib** [comment]
I've created a pull request to your fork with some refactoring on this feature. Could you please apply it on your `odb` branch if you agree with these modifications? Then I can merge this pull request. Thanks.

**Comment by mcserep** [comment]
Looks and works good, I accepted it.

**Comment by mcserep** [comment]
Partially superseded #270

**Pull request merged**
