### PR TITLE
Integrating the Haskell service

### PR DESCRIPTION
**Pull request by nboldi**
Only the C++ sources are included. Haskell files are here: https://github.com/nboldi/codecompass-haskell-plugin/tree/master/service-experiment

### CODE REVIEW

**Comment by mcserep** [comment]
CI probably fails due to outdated version of original codebase. Try updating it from the master branch.

**Comment by mcserep** [comment]
Since there has been no update on this PR over a year and the current version is still much in a state of *work in progress*, I close it. Of course it can be reopened if the task is continued.

**Comment by zporky** [comment]
I estimate that this project has around 50% readiness state.  Thanks for
closingthe ticket.

Máté Cserép <notifications@github.com> ezt írta (időpont: 2020. júl. 25.,
Szo, 18:01):

**Comment by intjftw** [comment]
Maybe we could give it to talented students to finish if Boldizsár does not intend to further work on it.

**Pull request closed without merging**
