### PR TITLE
Fix non existing type hash.

### PR DESCRIPTION
**Pull request by csordasmarton**
Fix non existing type hash.

### CODE REVIEW

**Comment by bruntib** [comment]
Could you please attach a code fragment in which there is a type with empty mangled name?

**Comment by bruntib** [comment]
Is this pull request related to #11?

**Comment by csordasmarton** [comment]
This commit solves an infotree problem, when we get the `Return type` of a function which return type is not a class type (E.g.: int, void) :
1. The problem is when the `mangledName` of an astNode is empty, the `typeHash` of a CppEntity (e.g.: CppFunction, CppVariable) will be the value of `util::fnvHash("")`. This way if we get AstNodes for this typeHash, it will return a huge number of AstNode.
I couldn't reproduce this error on a simple code. I checked our LLVM parse database and I picked an action where this error is occured and I parsed only that action.
2. The other problem was in the `VisitDeclRefExpr` function we didn't handle all the cases (e.g.: `NonTypeTemplateParmDecl`). This way we inserted "empty" CppAstNode all the time.

**Comment by bruntib** [comment]
I can't see why storing -1 instead of the hash of the empty string solves this problem. If we get InfoTree for such an entity, all nodes with typeHash -1 will be returned.

**Comment by csordasmarton** [comment]
There isn't any node with `mangledNameHash=-1` in the `CppAstNode` table. We use `npos` only to represent there isn't any node in the CppAstNode with this mangledNameHash. We didn't insert an AST node with `mangledNameHash=-1` as I know.
This way if we get InfoTree for such an entity, there will be no entry for this mangledNameHash in the CppAstNode table.

**Comment by mcserep** [comment]
Closing this pull request as there have been no activity on it in a long time and unresolved questions still remained.
Feel free to reopen it if further progress has been done. In such a case, please also resolve the existing merge conflicts.

**Pull request closed without merging**
