### PR TITLE
Checking if the result of a query or query_one function is not empty or nullptr

### PR DESCRIPTION
**Pull request by matebelenyesi**

### CODE REVIEW

**Comment by whisperity** [comment]
Please rebase and squash the commits there's a back-and-forth diff added.

**Comment by mcserep** [comment]
Please add a short description what this PR is about. We know about it now, but documentation is required so we will know about it later.

**Comment by matebelenyesi** [comment]
I close this pull request, and open an other with the same changes, because i accidently merged not related commits here.

**Comment by mcserep** [comment]
You can also force-push the `querycheck` branch on your fork, in that case you can "reuse" this PR.

**Pull request closed without merging**
